export const OPEN_USER_CONFIGURATIONS =
  'client/UserConfigurations/OPEN_USER_CONFIGURATIONS';
export const LOAD_USER_CONFIGURATIONS =
  'client/UserConfigurations/LOAD_USER_CONFIGURATIONS';
export const LOAD_USER_CONFIGURATIONS_SUCCESS =
  'client/UserConfigurations/LOAD_USER_CONFIGURATIONS_SUCCESS';
export const LOAD_USER_CONFIGURATIONS_ERROR =
  'client/UserConfigurations/LOAD_USER_CONFIGURATIONS_ERROR';
export const CHANGE_NICKNAME_INPUT_VALUE =
  'client/UserConfigurations/CHANGE_NICKNAME_INPUT_VALUE';
export const SAVE_USER_CONFIGURATIONS =
  'client/UserConfigurations/SAVE_USER_CONFIGURATIONS';
export const SAVE_USER_CONFIGURATIONS_SUCCESS =
  'client/UserConfigurations/SAVE_USER_CONFIGURATIONS_SUCCESS';
export const SAVE_USER_CONFIGURATIONS_ERROR =
  'client/UserConfigurations/SAVE_USER_CONFIGURATIONS_ERROR';
export const CLOSE_USER_CONFIGURATION =
  'client/UserConfigurations/CLOSE_USER_CONFIGURATION';
